### ISSUE TITLE
Table row broken on block 219042 in explorer

### ISSUE THREAD

**Issue by hclivess** [maccaspacca/BismuthToolsWeb#11]

**Comment by maccaspacca** [comment]
Investigating

**Comment by maccaspacca** [comment]
This appears to break the html markup of the displayed page because the openfield contains html content. I will look at ways of detecting and stripping out this kind of content prior to display.

**Comment by maccaspacca** [comment]
Fix found - detect and prevent rendering of html content in openfield.

**Comment by hclivess** [comment]
Thanks!
