### ISSUE TITLE
Limit Ledger Query display

### ISSUE THREAD

**Issue by Adorid** [maccaspacca/BismuthToolsWeb#2]
Need to limit Ledger Query showed records, show by time or multiple pages.

**Comment by maccaspacca** [comment]
This is a problem with some addresses. I will look to limit to 100 records possibly with next and previous similar to block query.

**Comment by hclivess** [comment]
Hello, guys, the types inside ledger database have been changed and stuff like getting balances and ordering by timestamps should be faster by about 2300%
http://bismuth.cz/ledger.tar.gz is already updated

**Comment by maccaspacca** [comment]
Ledger query limited and is set in toolsconfig.ini via the display = arguement.
