### ISSUE TITLE
Recommendation on wording - empty wallets

### ISSUE THREAD

**Issue by hclivess** [maccaspacca/BismuthToolsWeb#8]
Hi, currently users with empty but created wallets see "Error !!! Block, address or hash not found. Maybe you entered bad data or nothing at all?". We should let them know that the case might be their wallet is empty. My friend got confused by it, thanks.

**Comment by maccaspacca** [comment]
Yes I agree. I will agree new wording with the team and then apply at the next convenient update.

**Comment by maccaspacca** [comment]
Wording changed - hopefully now less confusing
