### ISSUE TITLE
The blockex API is missing a command to request txid and get transaction info

### ISSUE THREAD

**Issue by untilted-document** [maccaspacca/BismuthToolsWeb#9]
The API page on the block explorer doesn't seem to cite a method I can use to turn a txid into info about the transaction - 

I can see http://bismuth.online/api/transaction/blocknumber=amount but I don't have blocknumber and amount. 

I also see http://bismuth.online/api/hash/somehashvalue but I think that takes a block hash and i don't have that either

I can put a txid into the Ledger Query form, and get results back detailing the transactrion. but there is no matching method for API. I'd rather not HTTP POST to the ledgerquery, and parse the HTML results..

**Comment by maccaspacca** [comment]
I agree. The API was written before txid was implemented. A major update is planned that will include an update and rewrite of the API (existing commands are expected to stay the same) to include new functions. The ETA for the update is 31st May 2018. If you wish me to make an earlier change to include txid in the API I will consider this.

**Comment by maccaspacca** [comment]
txid included in version 6.0.0
